### PR TITLE
Some features and fix 1 spelling mistake in README.md

### PR DESCRIPTION
**Pull request by shahoob**
I have multiple enchantments to propose.

- I found a spelling mistake in your README (line 69)
- I'm currently trying to improve your CI workflow
- I ran `npm audit fix`

At the time of writing this, it is still a WIP.
When it's ready, this PR will be undrafted.

### CODE REVIEW

**Review by origeva — COMMENTED** [review]
Why should we stop support for node versions 10 - 16?
Are cross-fetch supported versions vulnerable?
In this case, maybe we can switch http client to axios?

Your facts are fun, and I appreciate your wonderful commit messages.

**Comment by shahoob** [comment]
Node.js versions from 10 to 13 (which were LTS versions) are unsupported and will not receive new updates.
If they have critical vulnerabilities, they will not be fixed, and is generally not recommended for production use.
Check their [release schedule](https://github.com/nodejs/release#release-schedule) for latest info.
Note: v16 is still supported, just in maintenance. Still ready for production use. _(i think)_

I haven't checked if cross-fetch supported versions are vulnerable yet.
If I found one, maybe we can switch to axios.

**Comment by shahoob** [comment]
I updated actions/checkout in order to not use Node.js v12 for running it. (d0d342cac864b9973003b3bc5689716f5fceca6d)

**Comment by shahoob** [comment]
I don't know what else to add to this PR. Ready for merging

**Pull request merged**
